run:
	go run ./cmd/server

test:
	go test ./...

reset-dev:
	go run ./cmd/devreset --yes

service-start:
	./scripts/atthub-service.sh start

service-stop:
	./scripts/atthub-service.sh stop

service-restart:
	./scripts/atthub-service.sh restart

service-status:
	./scripts/atthub-service.sh status

service-logs:
	./scripts/atthub-service.sh logs
